---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safe-wallet-web.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-wallet-web.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
data:
  NEXT_PUBLIC_IS_PRODUCTION: "{{- .Values.config.isProduction }}"
  NEXT_PUBLIC_SAFE_VERSION: "1.3.0"
  {{- if .Values.config.isProduction }}
  NEXT_PUBLIC_GATEWAY_URL_PRODUCTION: "{{- .Values.config.gatewayUrl }}"
  {{- else }}
  NEXT_PUBLIC_GATEWAY_URL_STAGING: "{{- .Values.config.gatewayUrl }}"
  {{- end }}
  {{- if .Values.config.extraEnvVars }}
  {{ .Values.config.extraEnvVars | toYaml | nindent 2 }}
  {{- end }}